package com.example.me;

public enum SyntaxKind {
    NUMBER_TOKEN, BAD_TOKEN, STRING_TOKEN, WHITE_SPACE_TOKEN, PLUS_TOKEN, MINUS_TOKEN, STAR_TOKEN, SLASH_TOKEN,
    OPEN_PARENTHESES_TOKEN, CLOSE_PARENTHESES_TOKEN, END_OF_FILE_TOKEN, NUMBER_EXPRESSION, BINARY_EXPRESSION

}
